name: dataloader
channels:
  - ioos
  - odm2
dependencies:
  - python=2.7
  - numpy
  - pip
  - psycopg2
  - pymysql
  - sqlalchemy
  - sqlite
  - wheel
  - wxpython
  - pyyaml
  - openpyxl
  - odm2api
  - pip:
    - pyodbc
