# """Subclass of WizardSQLitePageView, which is generated by wxFormBuilder."""
#
# import wx
from wx import Panel, Button,  FileDialog, \
    DefaultPosition, DefaultSize,  \
    ID_ANY, ALL,  EXPAND,\
    ALIGN_CENTER_VERTICAL,  ALIGN_CENTER_HORIZONTAL, TE_PASSWORD, EVT_BUTTON,\
    FD_OPEN, ID_OK, FD_FILE_MUST_EXIST, FD_SAVE


from yodatools.dataloader.view.WizardDatabasePageView import WizardDatabasePageView


class WizardSQLitePageController(WizardDatabasePageView):
    def __init__(self, parent, title=''):
        super(WizardSQLitePageController, self).__init__(parent)
        self.title = title

        self.panel.choices = {
            'SQLite': 'sqlite'
        }
        self.panel.cbDatabaseType.SetItems(self.panel.choices.keys())
        self.panel.cbDatabaseType.SetStringSelection('SQLite')


        self.panel.txtDBName.Disable()
        self.panel.txtPass.Disable()
        self.panel.txtUser.Disable()
        self.panel.stDBName.Disable()
        self.panel.stPass.Disable()
        self.panel.stUser.Disable()
        self.panel.stServer.SetLabel("SQLite File Path:")


        self.btnBrowse = Button(self.panel, ID_ANY, 'Browse', DefaultPosition, DefaultSize, 0)  # noqa
        self.panel.btnSizer.Add(self.btnBrowse, 1, ALL | EXPAND | ALIGN_CENTER_VERTICAL | ALIGN_CENTER_HORIZONTAL, 5)  # noqa
        self.panel.Layout()
        # Connect Events.
        self.btnBrowse.Bind(EVT_BUTTON, self.OnBtnBrowse)


    def OnBtnBrowse(self, event):
        dialog = FileDialog(
            self,
            'ODM2 SQLite file',
            wildcard="SQLite File (*.sqlite)|*.sqlite",
            style=FD_SAVE
        )

        # with FileDialog(self, "Save XYZ file", wildcard="XYZ files (*.xyz)|*.xyz",
        #                    style=FD_SAVE | FD_OVERWRITE_PROMPT) as fileDialog:

        #the sqlite file must exist and have the tables generated for the code to work.
        if dialog.ShowModal() != ID_OK:
            return

        path = dialog.GetPath()
        dialog.Destroy()


        #TODO run sqlite generation file if this is a new sqlite file

        self.panel.txtServer.SetValue(path)

